### PR TITLE
fix: coro-channel attempts to resume running thread

### LINKED ISSUE #303: coro-channel: resuming before having a chance to yield
`coro_http.request("GET", "https://google.com", {}, "")`
would error with;
```
cannot resume running coroutine
stack traceback:
	/mnt/data/bilal/deps/coro-channel.lua:16: in function 'assertResume'
	/mnt/data/bilal/deps/coro-channel.lua:126: in function 'callback'
	/mnt/data/bilal/deps/secure-socket/biowrap.lua:43: in function 'write'
	/mnt/data/bilal/deps/coro-channel.lua:148: in function 'write'
	/mnt/data/bilal/deps/coro-http.lua:149: in function </mnt/data/bilal/deps/coro-http.lua:106>
	[C]: in function 'xpcall'
	[string "bundle:/deps/repl.lua"]:97: in function 'evaluateLine'
	[string "bundle:/deps/repl.lua"]:189: in function <[string "bundle:/deps/repl.lua"]:187>
stack traceback:
	[C]: in function 'error'
	/mnt/data/bilal/deps/coro-channel.lua:16: in function 'assertResume'
	/mnt/data/bilal/deps/coro-channel.lua:126: in function 'callback'
	/mnt/data/bilal/deps/secure-socket/biowrap.lua:43: in function 'write'
	/mnt/data/bilal/deps/coro-channel.lua:148: in function 'write'
	/mnt/data/bilal/deps/coro-http.lua:149: in function </mnt/data/bilal/deps/coro-http.lua:106>
```
While the request is very wrong (providing a body on GET) it shouldn't have produced such error. I am afraid it is affecting wider use-cases of the library.

I will be looking deeper into this.

### PR DESCRIPTION
**Pull request by Bilal2453**
Consider the following minimal-reproduction code:
```lua
local ssocket = {
  -- will finish the write instantly
  write = function(self, chunk, callback)
    callback()
    return true
  end,
  
  -- irrelevant, just to make the example work
  is_closing = function()
    return true
  end 
}

local write = require("coro-channel").wrapWrite(ssocket)
write("") -- it is important to provide any value here, because a nil value will close the socket instead of attempting a write
```
This will produce the following error
```
ncaught exception:
cannot resume running coroutine
stack traceback:
	/home/bilal/deps/coro-channel.lua:16: in function 'assertResume'
	/home/bilal/deps/coro-channel.lua:126: in function 'callback'
	/home/bilal/test.lua:5: in function 'write'
	/home/bilal/deps/coro-channel.lua:148: in function 'write'
	/home/bilal/test.lua:17: in function 'fn'
	[string "bundle:deps/require.lua"]:309: in function 'require'
	[string "bundle:/main.lua"]:128: in function <[string "bundle:/main.lua"]:20>
stack traceback:
	[C]: in function 'error'
	/home/bilal/deps/coro-channel.lua:16: in function 'assertResume'
	/home/bilal/deps/coro-channel.lua:126: in function 'callback'
	/home/bilal/test.lua:5: in function 'write'
	/home/bilal/deps/coro-channel.lua:148: in function 'write'
	/home/bilal/test.lua:17: in function 'fn'
	[string "bundle:deps/require.lua"]:309: in function 'require'
	[string "bundle:/main.lua"]:128: in function <[string "bundle:/main.lua"]:20>
stack traceback:
	[C]: in function 'error'
	[string "bundle:/deps/utils.lua"]:42: in function 'assertResume'
	[string "bundle:/init.lua"]:53: in function <[string "bundle:/init.lua"]:48>
	[C]: in function 'xpcall'
	[string "bundle:/init.lua"]:48: in function 'fn'
	[string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:266>
```

This happens because the write call at [coro-channel.lua#L148](https://github.com/luvit/lit/blob/master/deps/coro-channel.lua#L148 ) returns immediately, the callback produced by `wait()` is also called immediately, this callback will attempt to resume the current thread, but the `coroutine.yield` line has not yet been executed (since write finished instantly).

This minimal example is basically what happens when a socket is wrapped with `secure-socket` , which will attempt to optimize empty writes by returning immediately (in the flush function over [here](https://github.com/luvit/lit/blob/master/deps/secure-socket/biowrap.lua#L48-L51) it will execute the callback and return early).

Which leads to `https`/`wss` requests made by coro-net crash when code such as `require'coro-http'.request("POST", "https://google.com", {}, "")` is ran (secure-socket sees that we are trying to write an empty chunk for the payload, so it decides to just return early and immediately since such a write will be ignored by libuv anyways).

The solution suggested in this PR is to basically keep track of when the thread has yielded, and if the wait callback is called before we reach yield, then we don't bother with resuming current thread and just return, similar to what we did with `coro-split`.

fixes #303.

### CODE REVIEW

**Comment by Bilal2453** [comment]
Also added a test to catch those cases.

Worth noting some... annoyances, while writing that test I noticed if the writer returns with `return true, "this value should be ignored"` coro-channel will return that the write has failed (the return of `write()` will be `false` indicating a failure) but at the same time it won't attempt to close the handle (since `success` is true).  One part of the code thinks that it succeeded and doesn't attempt to close the socket, and the other part of the code simply checks if the second return is presented to treat it as an error.

Also, a `write()` could return failure indicated by either `nil` or `false`, it may returns either of the values depending on if the failure was picked up with the callback `callback("this is an error")` or with the write return `return false, "this is an error"`.

File: deps/coro-channel.lua [hunk 1]
```diff
@@ -120,10 +120,18 @@ end
 
 local function makeWrite(socket, closer)
 
+  local hasYielded, hasReturned
+  local success, err
```
Comment (truemedian) [inline deps/coro-channel.lua:124]: These variables hold state across writes and are not cleared before each use. This is a bug, after the first instantaneous write `hasReturned` will always be true.

**Review by truemedian — CHANGES_REQUESTED** [review]

File: deps/coro-channel.lua (hunk 1 above)
Comment (Bilal2453) [reply deps/coro-channel.lua:124]: Thanks for catching this one! I honestly was worried about it since the last time I tested a fix like this it completely killed my performance testing.  This was likely the culprit!

Should I just introduce an upvalue `resetStates` that gets called before write/close calls?

Comment (Bilal2453) [reply deps/coro-channel.lua]: Should be fixed. On `wait` calls we now reset the states, `wait` is called before any write/shutdown call, so it ensures the states always reset.

Expanded the tests to catch this mistake, the "mixed instant/delayed writes" test will now catch it.

**Comment by Bilal2453** [comment]
As I expanded the tests I noticed another state-related bug, consider the following code:

```lua
local ssocket = {
  write = function(_, _, callback)
    callback('callback failed')
    return true
  end,
  
  is_closing = function()
    return true
  end 
}

local write = require("coro-channel").wrapWrite(ssocket)
assert(write(""))
```
The control flow of this goes something like this:
1. We call `wait` which resets and prepares the states and upvalues.
2. The `wait()` callback is instantly called.
3. `err` is set to `"callback failed"` since the callback failed.
4. `success` is set to `true` (since the call succeed), `err` is set to nil.
5. `write` returns success, even though this actually failed.

Usually, the `err` value will be set by the `write` call itself (over in `success, err = write(...)`, then it is reused for the callback returned error, but since in this case the callback is executed first this is no more the case.

This is now fixed by separating the call error from the callback error and tracked by two separate states.

**Review by truemedian — APPROVED** [review]
In general I dislike the state that this change introduces, which makes it significantly harder to reason about what is happening in the control flow through these functions.

However if this fixes the bug I'm fine with introducing it and writing it off for "clean up later".

**Comment by Bilal2453** [comment]
This likely won't be the last fix we introduce for a problem like this.  I
also hate the complexity of this flow and it proved annoying as I got it
wrong the first 3 attempts.  What should the flow look like ideally if you
happen to have an idea?

**Comment by Bilal2453** [comment]
@squeek502 should be ready for merge.
